### ISSUE TITLE
Error: creating build container: copying system image from manifest list. Manjaro

### ISSUE THREAD

**Issue by Alexandrsv** [fat-tire/resolve#27] opened 2022-11-21 11:58 UTC
There was a problem installing

is it possible to fix this?

```
Manjaro
Docker version 20.10.21
```

```
./build.sh
During this build process, Blackmagic Design Pty. Ltd.'s License
Agreement for DaVinci Resolve [Studio] (18.1) will be extracted from
the zip file and displayed. You must carefully read the License Agreement
and agree to its terms and conditions before using DaVinci Resolve.
Similarly, some versions of NVIDIA's drivers also require acceptance of
a license, which is available at nvidia.com. You must review any applicable
license and agree to its terms and conditions before using the NVIDIA driver.
Do you agree to the above [y/N] y
Building the resolve:18.1 image...
WARN[0000] Reading allowed ID mappings: reading subuid mappings for user "alexandr" and subgid mappings for group "alexandr": no subuid ranges found for user "alexandr" in /etc/subuid 
WARN[0000] Found no UID ranges set aside for user "alexandr" in /etc/subuid. 
WARN[0000] Found no GID ranges set aside for user "alexandr" in /etc/subgid. 
STEP 1/16: FROM quay.io/centos/centos:stream9
Trying to pull quay.io/centos/centos:stream9...
Getting image source signatures
Copying blob 4ac1d6819b77 done  
Error: creating build container: copying system image from manifest list: writing blob: adding layer with blob "sha256:4ac1d6819b77566d3cee3dc4172247601164e2d6059757fb371b76f8f1fa411f": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /var/spool/mail: invalid argument): exit status 1
Build of resolve:18.1 is complete.  To run resolve, try:

./resolve.sh
```

```
./resolve.sh                                                                                                                         
non-network local connections being added to access control list
./resolve.sh: строка 39: podman: команда не найдена
The 'resolve' image wasn't found.  Build the Dockerfile first.

```

**Comment by cowmix** [comment] 2022-11-22 18:01
Hey @Alexandrsv, I see you have both podman AND Docker installed. The build script by defaults picks Podman over Docker.

First make sure Podman is as current as possible. I seen where recent updates to Podman have resolved issues like this for other users when building Dockerfiles for other apps (not specifically Resolve).  

The other thing I would try is specifically target Docker instead of Podman.  Here's how to target a specific container engine:

RESOLVE_CONTAINER_ENGINE=docker ./build.sh

**Comment by Alexandrsv** [comment] 2022-11-25 22:53
Thanks, it worked.

But unfortunately davinci does not work correctly with the files that I put in the mounted folder.

I'll try another time

**Comment by fat-tire** [comment] 2022-11-27 04:31
Cool!  If the problem is container-related, feel free to open another issue... closing this one :)

**Closed by fat-tire** 2022-11-27 04:31 UTC
